# Generated by Django 4.2.11 on 2024-03-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_type_transformer', '0002_csvfiles_data_type_alter_csvfiles_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfiles',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
